// SignUpFrame.java
// 2430 OOPs I Program 3
package logins;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class SignUpFrame extends JFrame
{

    private JButton fullregister_btn;
    private JButton goback_btn;
    private JComboBox<String> jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    private JTextField name_txt;
    private JTextField newpassword_txt;
    private JTextField newusername_txt;

    public SignUpFrame()
    {
        this.initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton goback_btn = new javax.swing.JButton();
        fullregister_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        name_txt = new javax.swing.JTextField();
        newusername_txt = new javax.swing.JTextField();
        newpassword_txt = new javax.swing.JTextField();
        this.setTitle("Sign Up Page");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setLabelFor(name_txt);
        jLabel1.setText("Enter First Name:");
        jLabel1.setToolTipText("");

        jLabel2.setLabelFor(newusername_txt);
        jLabel2.setText("Enter New Username:");
        jLabel2.setToolTipText("");

        jLabel3.setLabelFor(newpassword_txt);
        jLabel3.setText("Enter New Password:");
        jLabel3.setToolTipText("");

        goback_btn.setText("Cancel");
        goback_btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                goback_btnActionPerformed(evt);
            }
        });

        fullregister_btn.setText("Submit");
        fullregister_btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fullregister_btnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Student", "Professor", "Administrator" }));

        newusername_txt.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(goback_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(fullregister_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newpassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newusername_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(newusername_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newpassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goback_btn)
                    .addComponent(fullregister_btn))
                .addGap(28, 28, 28))
        );

        pack();
    } // </editor-fold>  

    private void goback_btnActionPerformed(ActionEvent evt)
    {
        this.setVisible(false);
    }

    private void fullregister_btnActionPerformed(ActionEvent evt)
    {
        SuccessFrame sp;
        ErrorFrame ep;
        boolean b;
        String newusername = this.newusername_txt.getText();
        String newpassword = this.newpassword_txt.getText();
        String newname = this.name_txt.getText();
        String role = (String) this.jComboBox1.getSelectedItem();
        Person temp = null;
        int roleNum = 0;
        if (newname == null || newpassword == null || newusername == null){
            ep = new ErrorFrame();
            ep.setVisible(true);
            this.name_txt.setText(null);
            this.newusername_txt.setText(null);
            this.newpassword_txt.setText(null);
            this.jComboBox1.setSelectedIndex(0);
        }
        if (role.equals("Student"))
        {
            roleNum = 1;
            temp = new Student(newname, newusername, newpassword, roleNum);
            b = LoginFrame.people.addPerson(temp);
            if (!b)
            {
                ep = new ErrorFrame();
                ep.setVisible(true);
            }
            else
            {
                this.name_txt.setText(null);
                this.newusername_txt.setText(null);
                this.newpassword_txt.setText(null);
                sp = new SuccessFrame();
                sp.setVisible(true);
            }
        }
        if (role.equals("Professor"))
        {
            roleNum = 2;
            temp = new Professor(newname, newusername, newpassword, roleNum);
            b = LoginFrame.people.addPerson(temp);
            if (!b)
            {
                ep = new ErrorFrame();
                ep.setVisible(true);
            }
            else
            {
                this.name_txt.setText(null);
                this.newusername_txt.setText(null);
                this.newpassword_txt.setText(null);
                sp = new SuccessFrame();
                sp.setVisible(true);
            }
        }
        if (role.equals("Administrator"))
        {
            roleNum = 3;
            temp = new Administrator(newname, newusername, newpassword, roleNum);
            b = LoginFrame.people.addPerson(temp);
            if (!b)
            {
                ep = new ErrorFrame();
                ep.setVisible(true);
            }
            else
            {
                this.name_txt.setText(null);
                this.newusername_txt.setText(null);
                this.newpassword_txt.setText(null);
                sp = new SuccessFrame();
                sp.setVisible(true);
            }
        }
        if (role.equals("Select Role"))
        {
            ep = new ErrorFrame();
            ep.setVisible(true);
        }
    }

    public static void main(String[] args)
    {
        try
        {
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            for (UIManager.LookAndFeelInfo info : UIManager.
                    getInstalledLookAndFeels())
            {
                if (!"Nimbus".equals(info.getName()))
                {
                    continue;
                }
                UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
        catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(SignUpFrame.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        EventQueue.invokeLater(new Runnable()
        {

            @Override
            public void run()
            {
                new SignUpFrame().setVisible(true);
            }
        });
    }

}
